AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    DynamoDBTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "roadsideUnitID"
                AttributeType: "N"
              - 
                AttributeName: "serviceLocationID"
                AttributeType: "N"
            BillingMode: "PAY_PER_REQUEST"
            TableName: "t_signal_info"
            KeySchema: 
              - 
                AttributeName: "roadsideUnitID"
                KeyType: "HASH"
              - 
                AttributeName: "serviceLocationID"
                KeyType: "RANGE"

    DynamoDBTable2:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "roadsideUnitID"
                AttributeType: "N"
              - 
                AttributeName: "serviceLocationID"
                AttributeType: "N"
            BillingMode: "PAY_PER_REQUEST"
            TableName: "t_communication_media_info"
            KeySchema: 
              - 
                AttributeName: "roadsideUnitID"
                KeyType: "HASH"
              - 
                AttributeName: "serviceLocationID"
                KeyType: "RANGE"

    DynamoDBTable3:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "roadsideUnitID"
                AttributeType: "N"
              - 
                AttributeName: "serviceLocationID"
                AttributeType: "N"
              - 
                AttributeName: "updateTimeInfo"
                AttributeType: "S"
            BillingMode: "PAY_PER_REQUEST"
            TableName: "t_service_location_info"
            KeySchema: 
              - 
                AttributeName: "serviceLocationID"
                KeyType: "HASH"
              - 
                AttributeName: "roadsideUnitID"
                KeyType: "RANGE"
            GlobalSecondaryIndexes: 
              - 
                IndexName: "serviceLocationID-updateTimeInfo-index"
                KeySchema: 
                  - 
                    AttributeName: "serviceLocationID"
                    KeyType: "HASH"
                  - 
                    AttributeName: "updateTimeInfo"
                    KeyType: "RANGE"
                Projection: 
                    ProjectionType: "ALL"
                ProvisionedThroughput: 
                    ReadCapacityUnits: 0
                    WriteCapacityUnits: 0

    DynamoDBTable4:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "roadsideUnitID"
                AttributeType: "N"
              - 
                AttributeName: "serviceLocationID"
                AttributeType: "N"
            BillingMode: "PAY_PER_REQUEST"
            TableName: "t_roadside_unit_info"
            KeySchema: 
              - 
                AttributeName: "roadsideUnitID"
                KeyType: "HASH"
              - 
                AttributeName: "serviceLocationID"
                KeyType: "RANGE"
            GlobalSecondaryIndexes: 
              - 
                IndexName: "serviceLocationID-roadsideUnitID-index"
                KeySchema: 
                  - 
                    AttributeName: "serviceLocationID"
                    KeyType: "HASH"
                  - 
                    AttributeName: "roadsideUnitID"
                    KeyType: "RANGE"
                Projection: 
                    ProjectionType: "ALL"
                ProvisionedThroughput: 
                    ReadCapacityUnits: 0
                    WriteCapacityUnits: 0

    DynamoDBTable5:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "roadsideUnitID"
                AttributeType: "N"
              - 
                AttributeName: "serviceLocationID"
                AttributeType: "N"
            BillingMode: "PAY_PER_REQUEST"
            TableName: "t_use_case_info"
            KeySchema: 
              - 
                AttributeName: "roadsideUnitID"
                KeyType: "HASH"
              - 
                AttributeName: "serviceLocationID"
                KeyType: "RANGE"

